In [1]:
# This is my Jupyter Notebook for notes taken whilst taking the "Data Scientist with Python" certification track.
# https://app.datacamp.com/learn/career-tracks/data-scientist-with-python

In [1]:
# ======================
# Introduction to Python
# ======================

# https://app.datacamp.com/learn/courses/intro-to-python-for-data-science

# operators behave differently across types
a = 5 * "a"
print(a)



aaaaa


In [2]:
a = 5 * 6
print(a)

30


In [3]:
# exponent e.g. 3 to power of 2
a = 3 ** 2
print(a)

9


In [4]:
# check type()
print(type(a))

<class 'int'>


In [5]:
# string concatenation requires explicit type conversion
print("3 to the power of 2 = " + str(a) + ", isn't that great?")

# other type conversions: bool(), float(), int()

3 to the power of 2 = 9, isn't that great?


In [6]:
# lists can use mixed types, and have nested lists
a = [ ["a", 1], ["b", 2], ["c", 3]]
print(a)

[['a', 1], ['b', 2], ['c', 3]]


In [7]:
a = ["a", 1, "b", 2, "c", 3]
print(a)

['a', 1, 'b', 2, 'c', 3]


In [8]:
# SUBSET
# 3rd element
print(a[2])

b


In [9]:
# last element
print(a[-1])

3


In [10]:
# 2nd last element
print(a[-2])

c


In [11]:
# SLICE
# 2nd, 3rd, and 4th element
print(a[1:4])

[1, 'b', 2]


In [12]:
# all elements up to 4th element
print(a[:4])

['a', 1, 'b', 2]


In [13]:
# all elements from 5th element onward
print(a[4:])

['c', 3]


In [39]:
# SUBSET LISTS OF LISTS
a = [["a", "b", "c"],
     ["d", "e", "f"],
     ["g", "h", "i"]]

# a[row][column]
# 3rd row, 1st column = "g"
print(a[2][0])

g


In [40]:
#  3rd row, 1st 2 columns i.e. a, b, d, e, g, h
print(a[2][:2])

['g', 'h']


In [41]:
# REPLACE ELEMENTS
a = ["a", "b", "c", "d", "e", "f"]
# replace 3rd element c with "z"
a[2] = "x"
print(a)

['a', 'b', 'x', 'd', 'e', 'f']


In [42]:
a[1:] = ["y", "z"]
print(a)

['a', 'y', 'z']


In [43]:
# EXTEND LIST
b = ["g", "h", "i", "j", "k", "l"]
a = a + b
print(a)

['a', 'y', 'z', 'g', 'h', 'i', 'j', 'k', 'l']


In [44]:
# DELETE LIST ELEMENT
# delete 2nd element
del(a[1])
print(a)

['a', 'z', 'g', 'h', 'i', 'j', 'k', 'l']


In [45]:
# delete 2nd last and 3rd last elements
del(a[-2:-4])

In [46]:
# PREVENT UPDATE TO REFERENCED LIST
b = list(a)
b[1] = "x"
print(b)
# notice only b gets updated, but not a
print(a)

['a', 'x', 'g', 'h', 'i', 'j', 'k', 'l']
['a', 'z', 'g', 'h', 'i', 'j', 'k', 'l']


In [47]:
# count elements in list
print(len(a))

8


In [48]:
# HELP
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [49]:
help(pow)

Help on built-in function pow in module builtins:

pow(base, exp, mod=None)
    Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments
    
    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.



In [50]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [51]:
# sorted has 3 args: iterable, key, reverse
print(sorted(a))

['a', 'g', 'h', 'i', 'j', 'k', 'l', 'z']


In [52]:
# change function behaviours via its arguments
b = sorted(list(a),reverse=True)
print(b)

['z', 'l', 'k', 'j', 'i', 'h', 'g', 'a']


In [53]:
# METHODS
# uppercase
a = "dictionary"
print(a.upper())


DICTIONARY


In [54]:
# count number of times the substring appears
print(a.count("i",0))

2


In [55]:
# LIST METHODS

# index of first matching element
a = [5, 4, 3, 2, 1, 4]
print(a.index(4))


1


In [56]:
# count instances of element
print(a.count(4))

2


In [57]:
# add elements to end of list
a.append(3)
a.append(2)
print(a)

[5, 4, 3, 2, 1, 4, 3, 2]


In [58]:
# reverse order of elements
a.reverse()
print(a)

[2, 3, 4, 1, 2, 3, 4, 5]


In [59]:
# IMPORT PACKAGE

import math as m
radius = 7
circumference = 2 * m.pi * radius
print(circumference)

43.982297150257104


In [60]:
import math as m
radius = 7
area = m.pi * radius ** 2
print(area)

153.93804002589985


In [61]:
# SELECTIVE IMPORT
from math import radians
radius = 1234
a = radians(12)
b = radius * a
print(b)


258.44835563532035


In [63]:
# selective import with aliased method
from scripy.linalg import inv as alias_inv
alias_inv([[1,2], [3,4]])

ModuleNotFoundError: No module named 'scripy'

In [64]:
# NUMPY

# convert list to NumPy array
a = [10, 15, 5, 35, 50, 10]
print(type(a))
import numpy as np
np_a = np.array(a)
print(type(np_a))

<class 'list'>
<class 'numpy.ndarray'>


In [65]:
# operators function differently between lists and NumPy array
import numpy as np

# list as a whole is muliplied and concatenated
a = a * 2
print(a)
# NumPy element values are multiplied
np_a = a * 2
print(np_a)

[10, 15, 5, 35, 50, 10, 10, 15, 5, 35, 50, 10]
[10, 15, 5, 35, 50, 10, 10, 15, 5, 35, 50, 10, 10, 15, 5, 35, 50, 10, 10, 15, 5, 35, 50, 10]


In [66]:
# boolean test works on NumPy array, but not lists
import numpy as np

a = [10, 15, 5, 35, 50, 10]
b = np.array(a) > 10
print(b)

[False  True False  True  True False]


In [67]:
# NumPy array must contain same data types, unlike list which can have a mix
# NumPy arrays enforce data coercion where possible
# e.g. boolean true and false are converted to 1 and 0
import numpy as np

a = np.array([False, 1, 2]) + np.array([0, True, 2])
print(a)

[0 2 4]


In [68]:
# subset NumPy array is the same as subsetting a list
a = [5, 10, 15, 20, 25, 30]
print(a[2:5])

import numpy as np
b = np.array(a)
print(b[2:5])

[15, 20, 25]
[15 20 25]


In [69]:
# check dimensions a.k.a. shape of NumPy array
a = [[10, 20],
     [30, 40],
     [50, 60],
     [70, 80]]

import numpy as np
b = np.array(a)
print(b.shape)

(4, 2)


In [70]:
# subset 2D array
a = [[10, 20, 30],
     [40, 50, 60],
     [70, 80, 90],
     [100, 110, 120]]

import numpy as np
b = np.array(a)

# print all elements in 3rd row
print(b[2, :])

# print all elements in 2nd column
print(b[:, 1])

# print 3rd row's 2nd element
print(b[2, 1])

[70 80 90]
[ 20  50  80 110]
80


In [71]:
# arithmetic on 2D NumPy array 
import numpy as np
a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
b = np.array([1, 2, 3]) 

print(a / b)

[[10. 10. 10.]
 [40. 25. 20.]
 [70. 40. 30.]]


In [72]:
# NumPy basic statistics
import numpy as np
a = np.array([[5, 2, 6],
              [7, 1, 3],
              [8, 9, 4]])

# mean for 2nd column
print(np.mean(a[:, 1]))

# median for 2nd row
print(np.median(a[1, :]))

# standard deviation for 3rd column
print(np.std(a[:, 2]))

# correlation between 1st and 2nd columns
print(np.corrcoef(a[:, 0], a[:, 1]))

4.0
3.0
1.247219128924647
[[1.         0.67584534]
 [0.67584534 1.        ]]


In [75]:
# filter NumPy array by value in another array
import numpy as np
a = np.array(['Red', 'Blue', 'Blue', 'Red', 'Blue', 'Red', 'Red'])
b = np.array([11, 2, 4, 33, 66, 5, 77])
c = b[a == 'Red']
d = b[a != 'Red']
print(c)
print(d)

# perform statistical operation on filtered array
print(np.median(c))
print(np.mean(d))

[11 33  5 77]
[ 2  4 66]
22.0
24.0


In [ ]:
# ======================
# Intermediate Python
# ======================

# https://campus.datacamp.com/courses/intermediate-python/

In [ ]:
# Line chart

import matplotlib.pyplot as plt
year = [1960, 1970, 1980, 1990, 2000, 2010, 2020]
australia_population_millions = [10.48, 12.51, 14.69, 17.07, 19.03, 22.03, 25.69]

plt.plot(year, australia_population_millions)
plt.show()

In [ ]:
# Scatter plot

import matplotlib.pyplot as plt
year = [1960, 1970, 1980, 1990, 2000, 2010, 2020]
australia_population_millions = [10.48, 12.51, 14.69, 17.07, 19.03, 22.03, 25.69]

plt.scatter(year, australia_population_millions)
plt.show()

In [ ]:
# apply logaritmic scale to axis
import matplotlib.pyplot as plt
year = [1960, 1970, 1980, 1990, 2000, 2010, 2020]
australia_gdppcapita_usd = [1810.51, 3304.68, 10208.58, 18249.71, 21853.78, 52134.31, 51720.37]
plt.scatter(year, australia_gdppcapita_usd)
plt.show()
plt.yscale('log')
plt.show()

In [ ]:
# Histogram
import matplotlib.pyplot as plt

# hist(values_to_bin, number_of_bins defaults to 10)
help(hist)

australian_age_sample = [5,8,11,14,65,71,80,15,19,25,28,32,36,39,43,47,52,56,59,64]

plt.hist(australian_age_sample, bins=3)
plt.show()

In [ ]:
# clear current plotted figure
import matplotlib.pyplot as plt
plt.clf()

In [ ]:
# CUSTOMISE PLOT
# add customisations before the .show() function
# use .yticks() function to define where y axis starts from
# .yticks([list of values to use], [list of labels to display])

import matplotlib.pyplot as plt
year = [1960, 1970, 1980, 1990, 2000, 2010, 2020]
australia_population_millions = [10.48, 12.51, 14.69, 17.07, 19.03, 22.03, 25.69]

# can manually add more data to existing lists
year = [1901, 1911, 1921, 1931, 1941, 1951] + year
australia_population_millions = [3.79, 4.49, 5.46, 6.53, 7.11, 8.42] + australia_population_millions

plt.plot(year, australia_population_millions)

plt.xlabel('Year')
plt.ylabel('Population')
plt.title('World Population Projections')
plt.yticks([0, 5, 10, 15, 20, 25, 27.5], ['0', '5M', '10M', '15M', '20M', '25M', ' '])

plt.show()